apply plugin: 'com.android.application'
def key = rootProject.ext.keystoreConfig
def v = rootProject.ext.version

android {
    compileSdkVersion v.comV
    defaultConfig {
        applicationId "com.beizi.androiddemo"
        minSdkVersion v.minV
        targetSdkVersion v.targetV
        versionCode 1
        versionName "1.0"
        multiDexEnabled = true
    }
    signingConfigs {
        sign {
            keyAlias key.keyAlias
            keyPassword key.keyPassword
            storeFile key.storeFile
            storePassword key.storePassword
        }
    }
    buildTypes {
        release {
            signingConfig signingConfigs.sign
            minifyEnabled true
            shrinkResources true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }

        debug {
            signingConfig signingConfigs.sign
            minifyEnabled false
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

}

repositories {
    flatDir {
        dirs '../libs'
    }
    maven { url 'https://jitpack.io' }
}

dependencies {

//    implementation project(':beizi:amps-adapter')
    implementation project(':beizi:beizi-lib')
}
