apply plugin: 'com.android.application'

def key = rootProject.ext.keystoreConfig
def v = rootProject.ext.version

android {
    compileSdkVersion v.comV

    defaultConfig {
        applicationId "com.meishu.meishu_sdk_demo"
        minSdkVersion v.minV
        targetSdkVersion v.targetV
        versionCode 30000
        versionName "3.0.0"
        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'
        multiDexEnabled true
    }

    signingConfigs {
        debug {
            keyAlias key.keyAlias
            keyPassword key.keyPassword
            storeFile key.storeFile
            storePassword key.storePassword
        }
    }

    buildTypes {
        debug {
            debuggable true
            signingConfig signingConfigs.debug
        }
        release {
            minifyEnabled true
            signingConfig signingConfigs.debug
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

repositories {
    flatDir {
        dirs '../admate-lib/libs',
                '../../adnetworklibs/pangle'
    }
}

dependencies {
    implementation project(':admate:admate-lib')
}
