apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
def key = rootProject.ext.keystoreConfig
def v = rootProject.ext.version

android {
    compileSdkVersion v.comV

    signingConfigs {
        sign {
            keyAlias key.keyAlias
            keyPassword key.keyPassword
            storeFile key.storeFile
            storePassword key.storePassword
        }
    }

    defaultConfig {
        applicationId "com.union_test.toutiao"
        minSdkVersion v.minV
        targetSdkVersion v.targetV
        versionCode 1
        versionName "4.0.0.0"

        multiDexEnabled true

        ndk {
            abiFilters 'armeabi', 'arm64-v8a', 'armeabi-v7a'
        }


        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        debug {
            debuggable true
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.sign
        }
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.sign
        }
    }

    lintOptions {
        checkReleaseBuilds false
    }
    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }
    ndkVersion "23.1.7779620"
}

repositories {
    flatDir {
        dirs '../libs', '../libs/adn', '../libs/adn/mtg', '../libs/adn/sigmob', '../libs/adapter',
                '../../adnetworklibs/pangle'
    }
    maven { url 'https://artifact.bytedance.com/repository/AwemeOpenSDK' }

}

dependencies {
    implementation project(':gromore:gromore-lib')
    implementation(name: "Baidu_MobAds_SDK-release_v9.371", ext: 'aar')

}
