apply plugin: 'com.android.library'

android {
    compileSdkVersion 34
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 34
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    libraryVariants.all { variant ->
        variant.outputs.all { output ->
            if (outputFile != null && outputFileName.endsWith('.aar')) {
                def fileName = "adgain_mediatom_adapter_${rootProject.extractVersionFromAar()}.aar"
                outputFileName = fileName
            }
        }
    }

}


dependencies {
    compileOnly fileTree(include: ['*.jar', '*.aar'], dir: '../libs')
    compileOnly fileTree(include: ['*.jar', '*.aar'], dir: '../../adgainlibs')

}
