apply plugin: 'com.android.library'

android {
    compileSdkVersion 29

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 29
        versionCode 202410151
        versionName "4.603.1473.10151"
    }

    buildTypes {
        release {
//            minifyEnabled true
//            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    repositories {
        flatDir {
            dirs 'libs','../jiguang/libs'
        }
    }

    libraryVariants.all { variant ->
        variant.outputs.all { output ->
            if (outputFile != null && outputFileName.endsWith('.aar')) {
                def dir = getParent().projectDir.path + "/jiguang/libs/"
                def fileName = "adgain_jiguang_adapter_${rootProject.extractVersionFromAar(dir)}.aar"
                outputFileName = fileName
            }
        }
    }

}


dependencies {
    compileOnly "cn.jiguang.sdk.ad:core:3.9.5.10153"
    compileOnly(name: 'adgain-sdk-4.2.2', ext: 'aar')

}
