apply plugin: 'com.android.library'
def v = rootProject.ext.version

android {
    compileSdkVersion v.comV

    defaultConfig {
        minSdkVersion v.minV
        targetSdkVersion v.targetV
        versionCode 202410151
        versionName "4.603.1473.10151"
    }

    buildTypes {
        release {
//            minifyEnabled true
//            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    libraryVariants.all { variant ->
        variant.outputs.all { output ->
            if (outputFile != null && outputFileName.endsWith('.aar')) {
                def fileName = "adgain_jiguang_adapter_${rootProject.extractVersionFromAar()}.aar"
                outputFileName = fileName
            }
        }
    }

}


dependencies {
    compileOnly "cn.jiguang.sdk.ad:core:3.9.5.10153"
    compileOnly fileTree(include: ['*.jar', '*.aar'], dir: '../../adgainlibs')

}
