apply plugin: 'com.android.application'
def key = rootProject.ext.keystoreConfig
def v = rootProject.ext.version

android {
    compileSdkVersion v.targetV
    defaultConfig {
        applicationId "com.adgain.adapter" // 包名不能修改，极光对APPID和包名有校验
        minSdkVersion v.minV
        targetSdkVersion v.targetV
        versionCode 202410151
        versionName "202410151"
        multiDexEnabled true
    }

    signingConfigs {
        sign {
            keyAlias key.keyAlias
            keyPassword key.keyPassword
            storeFile key.storeFile
            storePassword key.storePassword
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.sign
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
        debug {
            signingConfig signingConfigs.sign
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    testOptions {
        unitTests {
            includeAndroidResources = true
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }



    repositories {

        flatDir {
            dirs '../libs'
        }
    }

    android.applicationVariants.all {
        variant ->
            variant.outputs.all {
                //这里修改apk文件名
                outputFileName = "ADJgSdkDemo-V${variant.versionName}.apk"
            }
    }
}

dependencies {
    implementation project(':jiguang:jiguang-lib')
    implementation fileTree(include: ['*.jar', '*.aar'], dir: '../libs')
    implementation fileTree(include: ['*.jar', '*.aar'], dir: '../../adgainlibs')
    implementation fileTree(include: ['*.jar', '*.aar'], dir: '../../adnetworklibs/oaid')
}
