apply plugin: 'com.android.library'

android {
    compileSdkVersion 30
    buildToolsVersion "30.0.2"

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 1
        versionName "1.0.0"

        consumerProguardFiles "consumer-rules.pro"
    }

    buildTypes {
        release {
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lintOptions {
        abortOnError false
    }
    libraryVariants.all { variant ->
        variant.outputs.all { output ->
            if (outputFile != null && outputFileName.endsWith('.aar')) {
                def fileName = "adgain_gromore_adapter_${rootProject.extractVersionFromAar()}.aar"
                outputFileName = fileName
            }
        }
    }

}

dependencies {
    compileOnly fileTree(include: ['*.jar', '*.aar'], dir: '../gm/libs/open_ad_sdk_6.8.1.7.aar')
    compileOnly fileTree(include: ['*.jar', '*.aar'], dir: '../../adgainlibs')
}


