plugins {
    id 'com.android.library'
}

android {
    compileSdk 33

    defaultConfig {
        minSdk 21
        targetSdk 33

        consumerProguardFiles "consumer-rules.pro"
        buildConfigField "String", "buildAdapterTs", "\"${new Date().format('yyyy-MM-dd HH:mm:ss')}\""

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        testOptions {
            unitTests {
                includeAndroidResources = true
            }
        }


    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    libraryVariants.all { variant ->
        variant.outputs.all { output ->
            if (outputFile != null && outputFileName.endsWith('.aar')) {
                def fileName = "adgain_tobid_adapter_${rootProject.extractVersionFromAar()}.aar"
                outputFileName = fileName
            }
        }
    }
}

dependencies {
    compileOnly fileTree(include: ['*.jar', '*.aar'], dir: '../tobid/libs')
    compileOnly fileTree(include: ['*.jar', '*.aar'], dir: '../../adgainlibs')
    compileOnly "com.github.bumptech.glide:glide:4.9.0"
    
    testImplementation 'junit:junit:4.13.2'
    testImplementation 'org.mockito:mockito-core:3.11.2'
    testImplementation 'org.robolectric:robolectric:4.8.1'
}