apply plugin: 'com.android.library'

android {
    compileSdkVersion 34
    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 34
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    libraryVariants.all { variant ->
        variant.outputs.all { output ->
            if (outputFile != null && outputFileName.endsWith('.aar')) {
                def dir = getParent().projectDir.path + "/taku/libs"
                def fileName = "adgain_taku_adapter_${rootProject.extractVersionFromAar(dir)}.aar"
                outputFileName = fileName
            }
        }
    }

}


dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])

    compileOnly(name: 'adgain-sdk-4.2.2', ext: 'aar')

    compileOnly(name: 'anythink_core', ext: 'aar')
    compileOnly(name: 'anythink_native', ext: 'aar')
    compileOnly(name: 'anythink_interstitial', ext: 'aar')
    compileOnly(name: 'anythink_rewardvideo', ext: 'aar')
    compileOnly(name: 'anythink_splash', ext: 'aar')
    compileOnly(name: 'anythink_banner', ext: 'aar')
    compileOnly(name: 'anythink_china_core', ext: 'aar')
}

repositories {
    flatDir {
        dirs '../taku/libs'
    }
}